# Generated by Django 2.0.2 on 2019-06-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='普通会员表',
            name='用户头像',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
