# Generated by Django 2.0.2 on 2019-07-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_普通会员表_用户头像'),
    ]

    operations = [
        migrations.AlterField(
            model_name='普通会员表',
            name='用户头像',
            field=models.CharField(default='akari.jpg', max_length=255),
        ),
    ]
